### ISSUE TITLE
Use nodejs version instead of browser

### ISSUE THREAD

**Issue by mubaidr** [misha-marinenko-official/BrainIDE#1]
Use node.js version (by using require) which will help in development by emitting better errors. 

https://github.com/misha-marinenko-official/BrainIDE/blob/50eb8e0ec6996cf66566cda58e926f5e7372d82b/app/index.html#L14

**Comment by misha-marinenko-official** [comment]
Maybe you can do this?
 im dont have mac with me right now. @mubaidr

**Comment by misha-marinenko-official** [comment]
Ok i will take this.
